package com.crm.entity;

public class AfterServiceProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_service_project.主键id
     *
     * @mbggenerated
     */
    private Long 主键id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_service_project.service_category
     *
     * @mbggenerated
     */
    private Integer serviceCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_service_project.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column after_service_project.fee_scale
     *
     * @mbggenerated
     */
    private Double feeScale;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    public AfterServiceProject(Long 主键id, Integer serviceCategory, String content, Double feeScale) {
        this.主键id = 主键id;
        this.serviceCategory = serviceCategory;
        this.content = content;
        this.feeScale = feeScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    public AfterServiceProject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_service_project.主键id
     *
     * @return the value of after_service_project.主键id
     *
     * @mbggenerated
     */
    public Long get主键id() {
        return 主键id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_service_project.主键id
     *
     * @param 主键id the value for after_service_project.主键id
     *
     * @mbggenerated
     */
    public void set主键id(Long 主键id) {
        this.主键id = 主键id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_service_project.service_category
     *
     * @return the value of after_service_project.service_category
     *
     * @mbggenerated
     */
    public Integer getServiceCategory() {
        return serviceCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_service_project.service_category
     *
     * @param serviceCategory the value for after_service_project.service_category
     *
     * @mbggenerated
     */
    public void setServiceCategory(Integer serviceCategory) {
        this.serviceCategory = serviceCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_service_project.content
     *
     * @return the value of after_service_project.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_service_project.content
     *
     * @param content the value for after_service_project.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column after_service_project.fee_scale
     *
     * @return the value of after_service_project.fee_scale
     *
     * @mbggenerated
     */
    public Double getFeeScale() {
        return feeScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column after_service_project.fee_scale
     *
     * @param feeScale the value for after_service_project.fee_scale
     *
     * @mbggenerated
     */
    public void setFeeScale(Double feeScale) {
        this.feeScale = feeScale;
    }
}