package com.crm.entity;

import java.util.Date;

public class Bill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.contract_id
     *
     * @mbggenerated
     */
    private Long contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.ammount
     *
     * @mbggenerated
     */
    private Double ammount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.balance
     *
     * @mbggenerated
     */
    private Boolean balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.actual_end_date
     *
     * @mbggenerated
     */
    private Date actualEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
    public Bill(Long id, Long orderId, Long contractId, Long customerId, String unit, String number, String remark, Double ammount, Boolean balance, Integer type, String account, Date endDate, Date actualEndDate) {
        this.id = id;
        this.orderId = orderId;
        this.contractId = contractId;
        this.customerId = customerId;
        this.unit = unit;
        this.number = number;
        this.remark = remark;
        this.ammount = ammount;
        this.balance = balance;
        this.type = type;
        this.account = account;
        this.endDate = endDate;
        this.actualEndDate = actualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
    public Bill() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id
     *
     * @return the value of bill.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id
     *
     * @param id the value for bill.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.order_id
     *
     * @return the value of bill.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.order_id
     *
     * @param orderId the value for bill.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.contract_id
     *
     * @return the value of bill.contract_id
     *
     * @mbggenerated
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.contract_id
     *
     * @param contractId the value for bill.contract_id
     *
     * @mbggenerated
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.customer_id
     *
     * @return the value of bill.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.customer_id
     *
     * @param customerId the value for bill.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.unit
     *
     * @return the value of bill.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.unit
     *
     * @param unit the value for bill.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.number
     *
     * @return the value of bill.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.number
     *
     * @param number the value for bill.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.remark
     *
     * @return the value of bill.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.remark
     *
     * @param remark the value for bill.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.ammount
     *
     * @return the value of bill.ammount
     *
     * @mbggenerated
     */
    public Double getAmmount() {
        return ammount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.ammount
     *
     * @param ammount the value for bill.ammount
     *
     * @mbggenerated
     */
    public void setAmmount(Double ammount) {
        this.ammount = ammount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.balance
     *
     * @return the value of bill.balance
     *
     * @mbggenerated
     */
    public Boolean getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.balance
     *
     * @param balance the value for bill.balance
     *
     * @mbggenerated
     */
    public void setBalance(Boolean balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.type
     *
     * @return the value of bill.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.type
     *
     * @param type the value for bill.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.account
     *
     * @return the value of bill.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.account
     *
     * @param account the value for bill.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.end_date
     *
     * @return the value of bill.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.end_date
     *
     * @param endDate the value for bill.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.actual_end_date
     *
     * @return the value of bill.actual_end_date
     *
     * @mbggenerated
     */
    public Date getActualEndDate() {
        return actualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.actual_end_date
     *
     * @param actualEndDate the value for bill.actual_end_date
     *
     * @mbggenerated
     */
    public void setActualEndDate(Date actualEndDate) {
        this.actualEndDate = actualEndDate;
    }
}