package com.crm.entity;

import java.util.Date;

public class ComplainRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.creator_id
     *
     * @mbggenerated
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.executor_id
     *
     * @mbggenerated
     */
    private Long executorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.produce_id
     *
     * @mbggenerated
     */
    private Long produceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.service_id
     *
     * @mbggenerated
     */
    private Long serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.execute_date
     *
     * @mbggenerated
     */
    private Date executeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.executed
     *
     * @mbggenerated
     */
    private Boolean executed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complain_record.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_record
     *
     * @mbggenerated
     */
    public ComplainRecord(Long id, Integer category, String content, Long creatorId, Long executorId, Long produceId, Long serviceId, Date createDate, Date executeDate, Boolean executed, Long customerId) {
        this.id = id;
        this.category = category;
        this.content = content;
        this.creatorId = creatorId;
        this.executorId = executorId;
        this.produceId = produceId;
        this.serviceId = serviceId;
        this.createDate = createDate;
        this.executeDate = executeDate;
        this.executed = executed;
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_record
     *
     * @mbggenerated
     */
    public ComplainRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.id
     *
     * @return the value of complain_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.id
     *
     * @param id the value for complain_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.category
     *
     * @return the value of complain_record.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.category
     *
     * @param category the value for complain_record.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.content
     *
     * @return the value of complain_record.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.content
     *
     * @param content the value for complain_record.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.creator_id
     *
     * @return the value of complain_record.creator_id
     *
     * @mbggenerated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.creator_id
     *
     * @param creatorId the value for complain_record.creator_id
     *
     * @mbggenerated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.executor_id
     *
     * @return the value of complain_record.executor_id
     *
     * @mbggenerated
     */
    public Long getExecutorId() {
        return executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.executor_id
     *
     * @param executorId the value for complain_record.executor_id
     *
     * @mbggenerated
     */
    public void setExecutorId(Long executorId) {
        this.executorId = executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.produce_id
     *
     * @return the value of complain_record.produce_id
     *
     * @mbggenerated
     */
    public Long getProduceId() {
        return produceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.produce_id
     *
     * @param produceId the value for complain_record.produce_id
     *
     * @mbggenerated
     */
    public void setProduceId(Long produceId) {
        this.produceId = produceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.service_id
     *
     * @return the value of complain_record.service_id
     *
     * @mbggenerated
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.service_id
     *
     * @param serviceId the value for complain_record.service_id
     *
     * @mbggenerated
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.create_date
     *
     * @return the value of complain_record.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.create_date
     *
     * @param createDate the value for complain_record.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.execute_date
     *
     * @return the value of complain_record.execute_date
     *
     * @mbggenerated
     */
    public Date getExecuteDate() {
        return executeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.execute_date
     *
     * @param executeDate the value for complain_record.execute_date
     *
     * @mbggenerated
     */
    public void setExecuteDate(Date executeDate) {
        this.executeDate = executeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.executed
     *
     * @return the value of complain_record.executed
     *
     * @mbggenerated
     */
    public Boolean getExecuted() {
        return executed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.executed
     *
     * @param executed the value for complain_record.executed
     *
     * @mbggenerated
     */
    public void setExecuted(Boolean executed) {
        this.executed = executed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complain_record.customer_id
     *
     * @return the value of complain_record.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complain_record.customer_id
     *
     * @param customerId the value for complain_record.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}