package com.crm.entity;

import java.util.Date;

public class Contract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.client_id
     *
     * @mbggenerated
     */
    private Long clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.salesman_id
     *
     * @mbggenerated
     */
    private Long salesmanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.verify_status
     *
     * @mbggenerated
     */
    private Boolean verifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.verify_opinion
     *
     * @mbggenerated
     */
    private String verifyOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.execute_status
     *
     * @mbggenerated
     */
    private Integer executeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.deadline
     *
     * @mbggenerated
     */
    private Date deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbggenerated
     */
    public Contract(Long id, Long clientId, Long salesmanId, Boolean verifyStatus, String verifyOpinion, String details, Integer category, Integer executeStatus, Double money, Date deadline, Date createDate) {
        this.id = id;
        this.clientId = clientId;
        this.salesmanId = salesmanId;
        this.verifyStatus = verifyStatus;
        this.verifyOpinion = verifyOpinion;
        this.details = details;
        this.category = category;
        this.executeStatus = executeStatus;
        this.money = money;
        this.deadline = deadline;
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbggenerated
     */
    public Contract() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.id
     *
     * @return the value of contract.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.id
     *
     * @param id the value for contract.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.client_id
     *
     * @return the value of contract.client_id
     *
     * @mbggenerated
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.client_id
     *
     * @param clientId the value for contract.client_id
     *
     * @mbggenerated
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.salesman_id
     *
     * @return the value of contract.salesman_id
     *
     * @mbggenerated
     */
    public Long getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.salesman_id
     *
     * @param salesmanId the value for contract.salesman_id
     *
     * @mbggenerated
     */
    public void setSalesmanId(Long salesmanId) {
        this.salesmanId = salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.verify_status
     *
     * @return the value of contract.verify_status
     *
     * @mbggenerated
     */
    public Boolean getVerifyStatus() {
        return verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.verify_status
     *
     * @param verifyStatus the value for contract.verify_status
     *
     * @mbggenerated
     */
    public void setVerifyStatus(Boolean verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.verify_opinion
     *
     * @return the value of contract.verify_opinion
     *
     * @mbggenerated
     */
    public String getVerifyOpinion() {
        return verifyOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.verify_opinion
     *
     * @param verifyOpinion the value for contract.verify_opinion
     *
     * @mbggenerated
     */
    public void setVerifyOpinion(String verifyOpinion) {
        this.verifyOpinion = verifyOpinion == null ? null : verifyOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.details
     *
     * @return the value of contract.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.details
     *
     * @param details the value for contract.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.category
     *
     * @return the value of contract.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.category
     *
     * @param category the value for contract.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.execute_status
     *
     * @return the value of contract.execute_status
     *
     * @mbggenerated
     */
    public Integer getExecuteStatus() {
        return executeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.execute_status
     *
     * @param executeStatus the value for contract.execute_status
     *
     * @mbggenerated
     */
    public void setExecuteStatus(Integer executeStatus) {
        this.executeStatus = executeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.money
     *
     * @return the value of contract.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.money
     *
     * @param money the value for contract.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.deadline
     *
     * @return the value of contract.deadline
     *
     * @mbggenerated
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.deadline
     *
     * @param deadline the value for contract.deadline
     *
     * @mbggenerated
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.create_date
     *
     * @return the value of contract.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.create_date
     *
     * @param createDate the value for contract.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Override
    public String toString() {
        return "Contract{" +
                "id=" + id +
                ", clientId=" + clientId +
                ", salesmanId=" + salesmanId +
                ", verifyStatus=" + verifyStatus +
                ", verifyOpinion='" + verifyOpinion + '\'' +
                ", details='" + details + '\'' +
                ", category=" + category +
                ", executeStatus=" + executeStatus +
                ", money=" + money +
                ", deadline=" + deadline +
                ", createDate=" + createDate +
                '}';
    }
}