package com.crm.entity;

public class Contact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.salesman_id
     *
     * @mbggenerated
     */
    private Long salesmanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.job
     *
     * @mbggenerated
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.importance
     *
     * @mbggenerated
     */
    private Integer importance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.personal_interest
     *
     * @mbggenerated
     */
    private String personalInterest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.vocation
     *
     * @mbggenerated
     */
    private String vocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated
     */
    public Contact(Long id, Long salesmanId, String name, String job, String telephone, Integer importance, String personalInterest, String province, String city, String area, String source, String vocation, String category) {
        this.id = id;
        this.salesmanId = salesmanId;
        this.name = name;
        this.job = job;
        this.telephone = telephone;
        this.importance = importance;
        this.personalInterest = personalInterest;
        this.province = province;
        this.city = city;
        this.area = area;
        this.source = source;
        this.vocation = vocation;
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated
     */
    public Contact() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.id
     *
     * @return the value of contact.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.id
     *
     * @param id the value for contact.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.salesman_id
     *
     * @return the value of contact.salesman_id
     *
     * @mbggenerated
     */
    public Long getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.salesman_id
     *
     * @param salesmanId the value for contact.salesman_id
     *
     * @mbggenerated
     */
    public void setSalesmanId(Long salesmanId) {
        this.salesmanId = salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.name
     *
     * @return the value of contact.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.name
     *
     * @param name the value for contact.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.job
     *
     * @return the value of contact.job
     *
     * @mbggenerated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.job
     *
     * @param job the value for contact.job
     *
     * @mbggenerated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.telephone
     *
     * @return the value of contact.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.telephone
     *
     * @param telephone the value for contact.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.importance
     *
     * @return the value of contact.importance
     *
     * @mbggenerated
     */
    public Integer getImportance() {
        return importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.importance
     *
     * @param importance the value for contact.importance
     *
     * @mbggenerated
     */
    public void setImportance(Integer importance) {
        this.importance = importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.personal_interest
     *
     * @return the value of contact.personal_interest
     *
     * @mbggenerated
     */
    public String getPersonalInterest() {
        return personalInterest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.personal_interest
     *
     * @param personalInterest the value for contact.personal_interest
     *
     * @mbggenerated
     */
    public void setPersonalInterest(String personalInterest) {
        this.personalInterest = personalInterest == null ? null : personalInterest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.province
     *
     * @return the value of contact.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.province
     *
     * @param province the value for contact.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.city
     *
     * @return the value of contact.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.city
     *
     * @param city the value for contact.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.area
     *
     * @return the value of contact.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.area
     *
     * @param area the value for contact.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.source
     *
     * @return the value of contact.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.source
     *
     * @param source the value for contact.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.vocation
     *
     * @return the value of contact.vocation
     *
     * @mbggenerated
     */
    public String getVocation() {
        return vocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.vocation
     *
     * @param vocation the value for contact.vocation
     *
     * @mbggenerated
     */
    public void setVocation(String vocation) {
        this.vocation = vocation == null ? null : vocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.category
     *
     * @return the value of contact.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.category
     *
     * @param category the value for contact.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}