package com.crm.entity;

import java.util.Date;

public class CustomerStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_statistics.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_statistics.department
     *
     * @mbggenerated
     */
    private Integer department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_statistics.update_number
     *
     * @mbggenerated
     */
    private Integer updateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_statistics.update_rate
     *
     * @mbggenerated
     */
    private Double updateRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_statistics.dropout_rate
     *
     * @mbggenerated
     */
    private Double dropoutRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_statistics.statistics_date
     *
     * @mbggenerated
     */
    private Date statisticsDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    public CustomerStatistics(Long id, Integer department, Integer updateNumber, Double updateRate, Double dropoutRate, Date statisticsDate) {
        this.id = id;
        this.department = department;
        this.updateNumber = updateNumber;
        this.updateRate = updateRate;
        this.dropoutRate = dropoutRate;
        this.statisticsDate = statisticsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    public CustomerStatistics() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_statistics.id
     *
     * @return the value of customer_statistics.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_statistics.id
     *
     * @param id the value for customer_statistics.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_statistics.department
     *
     * @return the value of customer_statistics.department
     *
     * @mbggenerated
     */
    public Integer getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_statistics.department
     *
     * @param department the value for customer_statistics.department
     *
     * @mbggenerated
     */
    public void setDepartment(Integer department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_statistics.update_number
     *
     * @return the value of customer_statistics.update_number
     *
     * @mbggenerated
     */
    public Integer getUpdateNumber() {
        return updateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_statistics.update_number
     *
     * @param updateNumber the value for customer_statistics.update_number
     *
     * @mbggenerated
     */
    public void setUpdateNumber(Integer updateNumber) {
        this.updateNumber = updateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_statistics.update_rate
     *
     * @return the value of customer_statistics.update_rate
     *
     * @mbggenerated
     */
    public Double getUpdateRate() {
        return updateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_statistics.update_rate
     *
     * @param updateRate the value for customer_statistics.update_rate
     *
     * @mbggenerated
     */
    public void setUpdateRate(Double updateRate) {
        this.updateRate = updateRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_statistics.dropout_rate
     *
     * @return the value of customer_statistics.dropout_rate
     *
     * @mbggenerated
     */
    public Double getDropoutRate() {
        return dropoutRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_statistics.dropout_rate
     *
     * @param dropoutRate the value for customer_statistics.dropout_rate
     *
     * @mbggenerated
     */
    public void setDropoutRate(Double dropoutRate) {
        this.dropoutRate = dropoutRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_statistics.statistics_date
     *
     * @return the value of customer_statistics.statistics_date
     *
     * @mbggenerated
     */
    public Date getStatisticsDate() {
        return statisticsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_statistics.statistics_date
     *
     * @param statisticsDate the value for customer_statistics.statistics_date
     *
     * @mbggenerated
     */
    public void setStatisticsDate(Date statisticsDate) {
        this.statisticsDate = statisticsDate;
    }

    @Override
    public String toString() {
        return "CustomerStatistics{" +
                "id=" + id +
                ", department=" + department +
                ", updateNumber=" + updateNumber +
                ", updateRate=" + updateRate +
                ", dropoutRate=" + dropoutRate +
                ", statisticsDate=" + statisticsDate +
                '}';
    }
}