package com.crm.entity;

import java.util.Date;

public class CustomerUpdateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_update_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_update_log.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_update_log.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_update_log.operator_time
     *
     * @mbggenerated
     */
    private Date operatorTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_update_log
     *
     * @mbggenerated
     */
    public CustomerUpdateLog(Long id, Long customerId, String content, Date operatorTime) {
        this.id = id;
        this.customerId = customerId;
        this.content = content;
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_update_log
     *
     * @mbggenerated
     */
    public CustomerUpdateLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_update_log.id
     *
     * @return the value of customer_update_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_update_log.id
     *
     * @param id the value for customer_update_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_update_log.customer_id
     *
     * @return the value of customer_update_log.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_update_log.customer_id
     *
     * @param customerId the value for customer_update_log.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_update_log.content
     *
     * @return the value of customer_update_log.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_update_log.content
     *
     * @param content the value for customer_update_log.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_update_log.operator_time
     *
     * @return the value of customer_update_log.operator_time
     *
     * @mbggenerated
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_update_log.operator_time
     *
     * @param operatorTime the value for customer_update_log.operator_time
     *
     * @mbggenerated
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }
}