package com.crm.entity;

import java.util.Date;

public class Flight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.start_place
     *
     * @mbggenerated
     */
    private String startPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.end_place
     *
     * @mbggenerated
     */
    private String endPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.airline
     *
     * @mbggenerated
     */
    private String airline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.distance
     *
     * @mbggenerated
     */
    private Double distance;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated
     */
    public Flight(Long id, String summary, Date startTime, Date endTime, String startPlace, String endPlace, Double price, String airline, Double distance) {
        this.id = id;
        this.summary = summary;
        this.startTime = startTime;
        this.endTime = endTime;
        this.startPlace = startPlace;
        this.endPlace = endPlace;
        this.price = price;
        this.airline = airline;
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flight
     *
     * @mbggenerated
     */
    public Flight() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.id
     *
     * @return the value of flight.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.id
     *
     * @param id the value for flight.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.summary
     *
     * @return the value of flight.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.summary
     *
     * @param summary the value for flight.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.start_time
     *
     * @return the value of flight.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.start_time
     *
     * @param startTime the value for flight.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.end_time
     *
     * @return the value of flight.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.end_time
     *
     * @param endTime the value for flight.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.start_place
     *
     * @return the value of flight.start_place
     *
     * @mbggenerated
     */
    public String getStartPlace() {
        return startPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.start_place
     *
     * @param startPlace the value for flight.start_place
     *
     * @mbggenerated
     */
    public void setStartPlace(String startPlace) {
        this.startPlace = startPlace == null ? null : startPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.end_place
     *
     * @return the value of flight.end_place
     *
     * @mbggenerated
     */
    public String getEndPlace() {
        return endPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.end_place
     *
     * @param endPlace the value for flight.end_place
     *
     * @mbggenerated
     */
    public void setEndPlace(String endPlace) {
        this.endPlace = endPlace == null ? null : endPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.price
     *
     * @return the value of flight.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.price
     *
     * @param price the value for flight.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.airline
     *
     * @return the value of flight.airline
     *
     * @mbggenerated
     */
    public String getAirline() {
        return airline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.airline
     *
     * @param airline the value for flight.airline
     *
     * @mbggenerated
     */
    public void setAirline(String airline) {
        this.airline = airline == null ? null : airline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.distance
     *
     * @return the value of flight.distance
     *
     * @mbggenerated
     */
    public Double getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.distance
     *
     * @param distance the value for flight.distance
     *
     * @mbggenerated
     */
    public void setDistance(Double distance) {
        this.distance = distance;
    }
}