package com.crm.entity;

public class Hotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.star_level
     *
     * @mbggenerated
     */
    private Integer starLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.package_price
     *
     * @mbggenerated
     */
    private Double packagePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated
     */
    public Hotel(Long id, String summary, Double price, String company, Integer starLevel, String address, Double packagePrice) {
        this.id = id;
        this.summary = summary;
        this.price = price;
        this.company = company;
        this.starLevel = starLevel;
        this.address = address;
        this.packagePrice = packagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbggenerated
     */
    public Hotel() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.id
     *
     * @return the value of hotel.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.id
     *
     * @param id the value for hotel.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.summary
     *
     * @return the value of hotel.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.summary
     *
     * @param summary the value for hotel.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.price
     *
     * @return the value of hotel.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.price
     *
     * @param price the value for hotel.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.company
     *
     * @return the value of hotel.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.company
     *
     * @param company the value for hotel.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.star_level
     *
     * @return the value of hotel.star_level
     *
     * @mbggenerated
     */
    public Integer getStarLevel() {
        return starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.star_level
     *
     * @param starLevel the value for hotel.star_level
     *
     * @mbggenerated
     */
    public void setStarLevel(Integer starLevel) {
        this.starLevel = starLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.address
     *
     * @return the value of hotel.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.address
     *
     * @param address the value for hotel.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.package_price
     *
     * @return the value of hotel.package_price
     *
     * @mbggenerated
     */
    public Double getPackagePrice() {
        return packagePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.package_price
     *
     * @param packagePrice the value for hotel.package_price
     *
     * @mbggenerated
     */
    public void setPackagePrice(Double packagePrice) {
        this.packagePrice = packagePrice;
    }
}