package com.crm.entity;

import java.util.Date;

public class Opportunity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.salesman_id
     *
     * @mbggenerated
     */
    private Long salesmanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.contact_id
     *
     * @mbggenerated
     */
    private Long contactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.client_name
     *
     * @mbggenerated
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.successful_probability
     *
     * @mbggenerated
     */
    private Double successfulProbability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.verify_status
     *
     * @mbggenerated
     */
    private Boolean verifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.verify_opinion
     *
     * @mbggenerated
     */
    private String verifyOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.assigned
     *
     * @mbggenerated
     */
    private Boolean assigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.assigned_salesman_id
     *
     * @mbggenerated
     */
    private Long assignedSalesmanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opportunity.assigned_date
     *
     * @mbggenerated
     */
    private Date assignedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opportunity
     *
     * @mbggenerated
     */
    public Opportunity(Long id, Long salesmanId, Long contactId, String source, String clientName, Double successfulProbability, String remark, Date createDate, Boolean verifyStatus, String verifyOpinion, Boolean assigned, Long assignedSalesmanId, Date assignedDate) {
        this.id = id;
        this.salesmanId = salesmanId;
        this.contactId = contactId;
        this.source = source;
        this.clientName = clientName;
        this.successfulProbability = successfulProbability;
        this.remark = remark;
        this.createDate = createDate;
        this.verifyStatus = verifyStatus;
        this.verifyOpinion = verifyOpinion;
        this.assigned = assigned;
        this.assignedSalesmanId = assignedSalesmanId;
        this.assignedDate = assignedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opportunity
     *
     * @mbggenerated
     */
    public Opportunity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.id
     *
     * @return the value of opportunity.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.id
     *
     * @param id the value for opportunity.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.salesman_id
     *
     * @return the value of opportunity.salesman_id
     *
     * @mbggenerated
     */
    public Long getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.salesman_id
     *
     * @param salesmanId the value for opportunity.salesman_id
     *
     * @mbggenerated
     */
    public void setSalesmanId(Long salesmanId) {
        this.salesmanId = salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.contact_id
     *
     * @return the value of opportunity.contact_id
     *
     * @mbggenerated
     */
    public Long getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.contact_id
     *
     * @param contactId the value for opportunity.contact_id
     *
     * @mbggenerated
     */
    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.source
     *
     * @return the value of opportunity.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.source
     *
     * @param source the value for opportunity.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.client_name
     *
     * @return the value of opportunity.client_name
     *
     * @mbggenerated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.client_name
     *
     * @param clientName the value for opportunity.client_name
     *
     * @mbggenerated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.successful_probability
     *
     * @return the value of opportunity.successful_probability
     *
     * @mbggenerated
     */
    public Double getSuccessfulProbability() {
        return successfulProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.successful_probability
     *
     * @param successfulProbability the value for opportunity.successful_probability
     *
     * @mbggenerated
     */
    public void setSuccessfulProbability(Double successfulProbability) {
        this.successfulProbability = successfulProbability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.remark
     *
     * @return the value of opportunity.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.remark
     *
     * @param remark the value for opportunity.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.create_date
     *
     * @return the value of opportunity.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.create_date
     *
     * @param createDate the value for opportunity.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.verify_status
     *
     * @return the value of opportunity.verify_status
     *
     * @mbggenerated
     */
    public Boolean getVerifyStatus() {
        return verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.verify_status
     *
     * @param verifyStatus the value for opportunity.verify_status
     *
     * @mbggenerated
     */
    public void setVerifyStatus(Boolean verifyStatus) {
        this.verifyStatus = verifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.verify_opinion
     *
     * @return the value of opportunity.verify_opinion
     *
     * @mbggenerated
     */
    public String getVerifyOpinion() {
        return verifyOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.verify_opinion
     *
     * @param verifyOpinion the value for opportunity.verify_opinion
     *
     * @mbggenerated
     */
    public void setVerifyOpinion(String verifyOpinion) {
        this.verifyOpinion = verifyOpinion == null ? null : verifyOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.assigned
     *
     * @return the value of opportunity.assigned
     *
     * @mbggenerated
     */
    public Boolean getAssigned() {
        return assigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.assigned
     *
     * @param assigned the value for opportunity.assigned
     *
     * @mbggenerated
     */
    public void setAssigned(Boolean assigned) {
        this.assigned = assigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.assigned_salesman_id
     *
     * @return the value of opportunity.assigned_salesman_id
     *
     * @mbggenerated
     */
    public Long getAssignedSalesmanId() {
        return assignedSalesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.assigned_salesman_id
     *
     * @param assignedSalesmanId the value for opportunity.assigned_salesman_id
     *
     * @mbggenerated
     */
    public void setAssignedSalesmanId(Long assignedSalesmanId) {
        this.assignedSalesmanId = assignedSalesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opportunity.assigned_date
     *
     * @return the value of opportunity.assigned_date
     *
     * @mbggenerated
     */
    public Date getAssignedDate() {
        return assignedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opportunity.assigned_date
     *
     * @param assignedDate the value for opportunity.assigned_date
     *
     * @mbggenerated
     */
    public void setAssignedDate(Date assignedDate) {
        this.assignedDate = assignedDate;
    }

    @Override
    public String toString() {
        return "Opportunity{" +
                "id=" + id +
                ", salesmanId=" + salesmanId +
                ", contactId=" + contactId +
                ", source='" + source + '\'' +
                ", clientName='" + clientName + '\'' +
                ", successfulProbability=" + successfulProbability +
                ", remark='" + remark + '\'' +
                ", createDate=" + createDate +
                ", verifyStatus=" + verifyStatus +
                ", verifyOpinion='" + verifyOpinion + '\'' +
                ", assigned=" + assigned +
                ", assignedSalesmanId=" + assignedSalesmanId +
                ", assignedDate=" + assignedDate +
                '}';
    }
}