package com.crm.entity;

import java.util.Date;

public class OrderList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderlist.ammount
     *
     * @mbggenerated
     */
    private Double ammount;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbggenerated
     */
    public OrderList(Long id, Integer type, Date createDate, Double ammount) {
        this.id = id;
        this.type = type;
        this.createDate = createDate;
        this.ammount = ammount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbggenerated
     */
    public OrderList() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.id
     *
     * @return the value of orderlist.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.id
     *
     * @param id the value for orderlist.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.type
     *
     * @return the value of orderlist.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.type
     *
     * @param type the value for orderlist.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.create_date
     *
     * @return the value of orderlist.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.create_date
     *
     * @param createDate the value for orderlist.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderlist.ammount
     *
     * @return the value of orderlist.ammount
     *
     * @mbggenerated
     */
    public Double getAmmount() {
        return ammount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderlist.ammount
     *
     * @param ammount the value for orderlist.ammount
     *
     * @mbggenerated
     */
    public void setAmmount(Double ammount) {
        this.ammount = ammount;
    }
}