package com.crm.entity;

import java.util.Date;

public class SalesRecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_records.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_records.opportunity_id
     *
     * @mbggenerated
     */
    private Long opportunityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_records.salesman_id
     *
     * @mbggenerated
     */
    private Long salesmanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_records.department_id
     *
     * @mbggenerated
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_records.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_records.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_records.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_records
     *
     * @mbggenerated
     */
    public SalesRecords(Long id, Long opportunityId, Long salesmanId, Integer departmentId, Boolean status, Double money, Date createDate) {
        this.id = id;
        this.opportunityId = opportunityId;
        this.salesmanId = salesmanId;
        this.departmentId = departmentId;
        this.status = status;
        this.money = money;
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_records
     *
     * @mbggenerated
     */
    public SalesRecords() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_records.id
     *
     * @return the value of sales_records.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_records.id
     *
     * @param id the value for sales_records.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_records.opportunity_id
     *
     * @return the value of sales_records.opportunity_id
     *
     * @mbggenerated
     */
    public Long getOpportunityId() {
        return opportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_records.opportunity_id
     *
     * @param opportunityId the value for sales_records.opportunity_id
     *
     * @mbggenerated
     */
    public void setOpportunityId(Long opportunityId) {
        this.opportunityId = opportunityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_records.salesman_id
     *
     * @return the value of sales_records.salesman_id
     *
     * @mbggenerated
     */
    public Long getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_records.salesman_id
     *
     * @param salesmanId the value for sales_records.salesman_id
     *
     * @mbggenerated
     */
    public void setSalesmanId(Long salesmanId) {
        this.salesmanId = salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_records.department_id
     *
     * @return the value of sales_records.department_id
     *
     * @mbggenerated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_records.department_id
     *
     * @param departmentId the value for sales_records.department_id
     *
     * @mbggenerated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_records.status
     *
     * @return the value of sales_records.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_records.status
     *
     * @param status the value for sales_records.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_records.money
     *
     * @return the value of sales_records.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_records.money
     *
     * @param money the value for sales_records.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_records.create_date
     *
     * @return the value of sales_records.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_records.create_date
     *
     * @param createDate the value for sales_records.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}