package com.crm.mapper.sale;

import com.crm.entity.CustomerStatistics;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "customerStatisticsMapper")
public interface CustomerStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int insert(CustomerStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int insertSelective(CustomerStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    CustomerStatistics selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerStatistics record);

    List<CustomerStatistics> selectAll();
}