package com.crm.mapper.sale;

import com.crm.entity.CustomerStatistics;

public interface CustomerStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int insert(CustomerStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int insertSelective(CustomerStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    CustomerStatistics selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_statistics
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerStatistics record);
}