package com.crm.mapper.sale;

import com.crm.entity.ExchangeInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "exchangeInfoMapper")
public interface ExchangeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_info
     *
     * @mbggenerated
     */
    int insert(ExchangeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_info
     *
     * @mbggenerated
     */
    int insertSelective(ExchangeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_info
     *
     * @mbggenerated
     */
    ExchangeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExchangeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExchangeInfo record);

    List<ExchangeInfo> selectAll();
}