package com.crm.mapper.sale;

import com.crm.entity.SalesRecords;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "salesRecordsMapper")
public interface SalesRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_records
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_records
     *
     * @mbggenerated
     */
    int insert(SalesRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_records
     *
     * @mbggenerated
     */
    int insertSelective(SalesRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_records
     *
     * @mbggenerated
     */
    SalesRecords selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SalesRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_records
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SalesRecords record);

    List<SalesRecords> findByDepartment();
    List<SalesRecords> findByWorker();
    List<SalesRecords> findByDepartmentOpportunity();
    List<SalesRecords> findByWorkerOpportunity();

}