package com.crm.mapper;

import com.crm.entity.AfterServiceProject;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.List;


@Mapper
@Component(value = "afterServiceProjectMapper")
public interface AfterServiceProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int insert(AfterServiceProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int insertSelective(AfterServiceProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    AfterServiceProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AfterServiceProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AfterServiceProject record);

    List<AfterServiceProject> selectAll();
}