package com.crm.mapper;

import com.crm.entity.AfterServiceSheet;

public interface AfterServiceSheetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_sheet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_sheet
     *
     * @mbggenerated
     */
    int insert(AfterServiceSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_sheet
     *
     * @mbggenerated
     */
    int insertSelective(AfterServiceSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_sheet
     *
     * @mbggenerated
     */
    AfterServiceSheet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_sheet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AfterServiceSheet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_sheet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AfterServiceSheet record);
}