package com.crm.mapper;

import com.crm.entity.AfterServiceProject;

public interface AfterServiceProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int insert(AfterServiceProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int insertSelective(AfterServiceProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    AfterServiceProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AfterServiceProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table after_service_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AfterServiceProject record);
}