package com.crm.mapper;

import com.crm.entity.Bill;
import com.crm.entity.Customer;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;
import com.crm.entity.finance.BillStatistic;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "billMapper")
public interface BillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
    int insert(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
    int insertSelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
    Bill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bill record);

    List<Bill> selectBillByCustomerID(Customer customer);
    List<Bill> getBillList();
    List<Bill> selectByType(Integer type);
    List<Bill> selectByBalance(Boolean balance);
    List<Bill> selectByTypeAndBalance(Integer type,Boolean balance);
    List<BillStatistic> selectByDate(String year,Integer type);
    List<Bill> selectByDay();
}