package com.crm.mapper;

import com.crm.entity.ComplainRecord;
import com.crm.entity.ProblemLibrary;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value="complainRecordMapper")
public interface ComplainRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_record
     *
     * @mbggenerated
     */
    int insert(ComplainRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_record
     *
     * @mbggenerated
     */
    int insertSelective(ComplainRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_record
     *
     * @mbggenerated
     */
    ComplainRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComplainRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complain_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComplainRecord record);

    List<ComplainRecord> selectAll();

    List<ComplainRecord> selectNotArrange();
    List<ComplainRecord> selectArranged();
}