package com.crm.mapper;

import com.crm.entity.CustomerUpdateLog;

public interface CustomerUpdateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_update_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_update_log
     *
     * @mbggenerated
     */
    int insert(CustomerUpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_update_log
     *
     * @mbggenerated
     */
    int insertSelective(CustomerUpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_update_log
     *
     * @mbggenerated
     */
    CustomerUpdateLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_update_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerUpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_update_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerUpdateLog record);
}