package com.crm.mapper;

import com.crm.entity.Opportunity;

public interface OpportunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opportunity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opportunity
     *
     * @mbggenerated
     */
    int insert(Opportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opportunity
     *
     * @mbggenerated
     */
    int insertSelective(Opportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opportunity
     *
     * @mbggenerated
     */
    Opportunity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opportunity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Opportunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opportunity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Opportunity record);
}