package com.crm.mapper;

import com.crm.entity.OrderList;

public interface OrderListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbggenerated
     */
    int insert(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbggenerated
     */
    int insertSelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbggenerated
     */
    OrderList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderlist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderList record);
}