package com.crm.mapper;

import com.crm.entity.WorkPlan;

public interface WorkPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan
     *
     * @mbggenerated
     */
    int insert(WorkPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan
     *
     * @mbggenerated
     */
    int insertSelective(WorkPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan
     *
     * @mbggenerated
     */
    WorkPlan selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkPlan record);
}